config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:new, :create, :destroy]

  resources :wikis

  get 'about' => 'welcome#about'
  
  resources :charges, only: [:new, :create, :destroy]

  devise_for :users
  
  root "wikis#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
  
  delegate :username, to: :user
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  after_initialize { self.role ||= :standard }
  enum role: [:standard, :premium, :admin]
  
  has_many :wikis
  has_many :collaborators
  # we need a different name for this association since
  # `has_many :wikis` is already taken.  This is one way to do it:
  has_many :wiki_collaborations, through: :collaborators, source: :wiki
  
  def collaborators
     Collaborator.find(user_id)
   end
   
   
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery
  
  before_action :authenticate_user!

   before_action :configure_permitted_parameters, if: :devise_controller?

   protected
  
   def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  class Amount
    def self.default
      @amount = 15_00
    end
    
    def self.refund
      @amount = 12_00
    end  
  end
  
  def new
     @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.email}",
     amount: Amount.default
   }
  end

  def create
     customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "BigMoney Membership - #{current_user.username}",
     currency: 'usd'
   )
   
  if charge.paid
     current_user.update(charge_id: charge.id, role: :premium)

     flash[:notice] = "Thanks for all the money, #{current_user.username}! Feel free to pay me again."
     redirect_to wikis_path
  end
   
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def destroy
    #stripe stuff to refund $12
   
     Stripe::Refund.create(
     charge: current_user.charge_id,
     amount: Amount.refund
   )
 
   flash[:notice] = "Your membership charge has been refunded (minus admin costs of $3.00), #{current_user.username}! Feel free to upgrade your membership again in the future."
   redirect_to wikis_path 
   
   #publicise all the private wikis
   current_user.wikis.update_all(private: false)
   current_user.standard!    
          
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  def new
    @collaborator = Collaborator.new
  end
  
  def create
    @collaborator = Collaborator.new
    @collaborator.user = User.where(username: params[:collaborator][:user]).first 
    @collaborator.wiki = Wiki.where(title: params[:title]).first
    user = User.find_by(username: params[:collaborator][:user])
    @wiki = Wiki.find_by(title: params[:title])
      
    if user
      @collaborator =  Collaborator.where(user: user, wiki: @wiki).first_or_initialize
      if @collaborator.persisted?
        flash[:alert] = 'User is already a collaborator'
        return redirect_to @wiki
      elsif @collaborator.save
        flash.now[:alert] = "#{user} can now collaborate on this wiki"
        redirect_to @wiki
      else
        flash.now[:alert] = "There was an error adding the collaborator. Please try again."
        render :new
      end
    else
      flash[:alert] = 'That user was not found'
      redirect_to @wiki
    end
  end

  def destroy
     @collaborator = Collaborator.find(params[:id])

     if @collaborator.destroy
       flash[:notice] = "The collaborator was deleted successfully."
       redirect_to wiki_path(params[:wiki])
     else
       flash.now[:alert] = "There was an error removing the collaborator."
       render :show
     end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
     @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collabs = @wiki.collaborators
  end

  def new
    @wiki = Wiki.new
  
  end  

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])

    authorize @wiki

    if @wiki.update(wiki_params)
      if @wiki.private
        flash[:notice] = "Private Wiki was saved. Only you can view this Wiki."
      else
        flash[:notice] = "Wiki was saved."
      end  
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def create
     @wiki = current_user.wikis.new(wiki_params)
     
     if(current_user.premium?)
        @wiki.private = params[:wiki][:private]
      else
        @wiki.private = false
     end  


    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def destroy
     @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

 private
   def wiki_params
     params.require(:wiki).permit(:title, :body, :private)
   end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    
   
  def markdown(text)
    options = {
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <% if current_user.role == 'standard' %>
     <h3>Click the button below to upgrade your account and enjoy all the benefits of premium membership, for only $15!</h3>
     <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
                                   data-key="<%= @stripe_btn_data[:key] %>" 
                                   data-amount="<%= @stripe_btn_data[:amount] %>" 
                                   data-description="<%= @stripe_btn_data[:description] %>" >
     </script>
   <% else %>
   <h3>Are you sure you want to downgrade to standard membership? Please note that if you continue, your private Wikis will be set to public. Your registration fee will be refunded, minus an admin charge of $3.</h3>
     <%= link_to "Confirm downgrade", @charge, method: :delete, class: 'btn1', data: { confirm: 'Are you sure you want to downgrade?' } %>
   <% end %>
 <% end %>

app/views/collaborators/new.html.erb
<h1>Add a collaborator to your private Wiki</h1>
<div class="wiki_create">
 <%= form_for @collaborator do |f| %>
 <div>
   <%= f.label :wiki_id %>
   <% wikititle = params[:wiki_title] %>
   <%= f.label wikititle %>
   <%= hidden_field_tag 'title', wikititle %>
  </div>
  <div>
    <%= f.label :user %>
    <%= f.text_field :user, class: 'text_collab' %>
  </div>
   <%= f.submit "Save", class: 'btn_small' %>
 <% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>BLOCIPEDIA</h1>
    <img src="https://image.ibb.co/dgra8R/bulb.png">
  </header>
  <div class="navigation">
    <div class="buttons">
      <ul>
        <li><%= link_to "Home", root_path, class: 'btn1' %></li>
        <li><%= link_to "My Wikis", wikis_path, class: 'btn1' %></li>
        <li><%= link_to "Create", new_wiki_path, class: 'btn1' %></li>
        <li><%= link_to "About", about_path, class: 'btn1' %></li>
        <% if user_signed_in? %>
          <li>
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn1' %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn1' ) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path, class: 'btn1' )  %>  
          </li>
        <% end %>
        <% if current_user && current_user.role == "standard" %>
          <li>
          <%= link_to('Upgrade Account', new_charge_path, class: 'btn1' ) %>        
          </li>
        <% elsif current_user %>
          <li>
            <%= link_to('Downgrade Account', new_charge_path, class: 'btn1' )  %>  
          </li>
          <% else %>
          <li>
            <%= link_to('Sign up!', new_user_registration_path, class: 'btn1' )  %>
          </li>
          <% end %>
      </ul>
    </div>
      <div class="user_details">
      <% if user_signed_in? %>
        <p>Signed in as: <strong><%= current_user.username %></strong></p>
      <% end %>
    </div>
  </div>
  
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="content">
  <%= yield %>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.2/showdown.min.js"></script>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/delete.html.erb
<h1>Wikis#delete</h1>
<p>Find me in app/views/wikis/delete.html.erb</p>

app/views/wikis/edit.html.erb
<div class="wiki_create">
  <%= form_for @wiki do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title, class: 'create_body' %>
   <div class="create">
       <%= f.label :body %>
       <%= f.text_area :body, class: 'create_body', id: 'wiki_body' %>
   </div>
   <%= f.submit "Save", class: 'btn_create' %>
 <% end %>
</div>
<div class="preview">
   <label>Preview</label>
   <div id="markdown_preview"></div>
</div>
<script type="text/javascript">
   showExisting();
</script>

app/views/wikis/index.html.erb
<h1>Recent Wikis</h1>
<% @wikis.each do |wiki| %>
   <p><%= link_to wiki.title, wiki %></p>
 <% end %>
 
 

app/views/wikis/new.html.erb
<div class="wiki_create">
 <%= form_for @wiki do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title, class: 'create_body' %>
   <div class="create">
       <%= f.label :body %>
       <%= f.text_area :body, class: 'create_body', id: 'wiki_body' %>
   </div>
   <% if current_user.role == 'premium' %>
     <div>
         <%= f.label :private %>
         <%= f.check_box :private %>
     </div>
   <% end %> 
   <%= f.submit "Save", class: 'btn_create' %>
 <% end %>
 </div>
 <div class="preview">
   <label>Preview</label>
   <div id="markdown_preview"></div>
 </div>

app/views/wikis/show.html.erb
 <div class="wiki">
   <h1><%= @wiki.title %></h1>
   <p><%= markdown(@wiki.body) %></p>
   
   
   <%= link_to "Edit this wiki", edit_wiki_path(@wiki), class: 'btn1' %>
   <%= link_to "Delete this wiki", @wiki, method: :delete, class: 'btn1', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   
  <% if @wiki.user == current_user && @wiki.private? %>
    <%= link_to 'Add Collaborators', new_collaborator_path(wiki_title: @wiki.title), class: 'btn1' %>
  <% end %>
  
  <% if policy(@wiki).manage_collaborators? %>
    <p>These are the collaborators on this wiki:</p>
    <% @collabs.each do |c| %>
      <li><%= c.username %>
      <%= link_to 'Remove Collaborator', collaborator_path(c.id, wiki: @wiki), method: :delete, data: {confirm: 'Are you sure you want to remove this collaborator?'} %></li>
    <% end%>
  <% end %>
   </div> 
 </div>
  

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>